---
output: github_document
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Projeto Final do Curso "R para Ciência de Dados I - Curso R"
O projeto_final é um trabalho de conclusão do curso "R para Ciência de Dados I" da Curso-R. Este trabalho tem por objetivo demonstrar a partir de uma análise exploratória sobre uma base de dados a aplicação dos recursos de pacotes como "dplyr", "ggplot2", "read_r", entre outros, que permitem a realização de manipulação de dados, construção de visualizações gráficas e leitura de bases.
A apresentação dos resultados é realizada por meio de um relatório em formato .Rmd (RMarkdown).

> Status: Concluído

## Campos do projeto/trabalho
+ Contextualização
+ Carregamento das Bibliotecas
+ Leitura da Base de Dados
+ Análise
+ Fatos Interessantes
+ Material de Apoio
+ Conclusão

## Pacotes Utilizados
+ _Dplyr_
+ _readr_
+ _ggplot2_
+ _knitr_
+ _shiny_
+ _kableExtra_
+ _ggrepel_
+ _here_

## Contato
+ Nome: Marcio Vakassugui
+ email: marcio.kazuhiko.vakassugui@gmail.com